name    'maisi-ganglia'
version '0.1.0'
source 'UNKNOWN'
author 'internal'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
